collections:
  posts:
    output: true
    permalink: /posts/:year/:slug
  archives: 
    output: true
url: "https://pts.careers" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap